UPDATE PRODUTOS SET PRECO = 79.90, ESTOQUE = '1'
WHERE IDPRODUTOS = 1;

UPDATE PRODUTOS SET TAMANHO = 'GG'
WHERE IDPRODUTOS = 3;

UPDATE PRODUTOS SET PRECO = 159.90
WHERE IDPRODUTOS = 9;

UPDATE PRODUTOS SET COR = 'AZUL MARINHO', ESTOQUE = '2'
WHERE IDPRODUTOS = 10;

UPDATE PRODUTOS SET DESCRICAO = 'CAMISA SOCIAL'
WHERE IDPRODUTOS = 15;

